interface Action {
  type: string;
  payload: string;
}

export const reducer = (state = initState, action: Action) => {
  switch (action.type) {
    case "SET_FILTER":
      return { ...state, filter: action.payload };
    default:
      return state;
  }
};

const initState = {
  filter: "",
  //list: [{ id: 1, name: "Алексей" }, { id: 2, name: "Мария" }, { id: 3, name: "Иван" }, { id: 4, name: "Елена" }, { id: 5, name: "Дмитрий" }, { id: 6, name: "София" }, { id: 7, name: "Максим" }, { id: 8, name: "Анастасия" }, { id: 9, name: "Николай" }, { id: 10, name: "Виктория" }, { id: 11, name: "Кирилл" }, { id: 12, name: "Ольга" }, { id: 13, name: "Андрей" }, { id: 14, name: "Наталья" }, { id: 15, name: "Григорий" }, { id: 16, name: "Татьяна" }, { id: 17, name: "Сергей" }, { id: 18, name: "Юлия" }, { id: 19, name: "Павел" }, { id: 20, name: "Екатерина" }],
  list: [
    { id: 1, name: "Алексей" },
    { id: 2, name: "Мария" },
    { id: 3, name: "Иван" },
    { id: 4, name: "Елена" },
    { id: 5, name: "Дмитрий" },
    { id: 6, name: "София" },
    { id: 7, name: "Максим" },
    { id: 8, name: "Анастасия" },
    { id: 9, name: "Николай" },
    { id: 10, name: "Виктория" },
    { id: 11, name: "Кирилл" },
    { id: 12, name: "Ольга" },
    { id: 13, name: "Андрей" },
    { id: 14, name: "Наталья" },
    { id: 15, name: "Григорий" },
    { id: 16, name: "Татьяна" },
    { id: 17, name: "Сергей" },
    { id: 18, name: "Юлия" },
    { id: 19, name: "Павел" },
    { id: 20, name: "Екатерина" },
    { id: 21, name: "Антон" },
    { id: 22, name: "Маргарита" },
    { id: 23, name: "Роман" },
    { id: 24, name: "Ксения" },
    { id: 25, name: "Владимир" },
    { id: 26, name: "Дарья" },
    { id: 27, name: "Константин" },
    { id: 28, name: "Алина" },
    { id: 29, name: "Михаил" },
    { id: 30, name: "Полина" },
    { id: 31, name: "Артур" },
    { id: 32, name: "Евгения" },
    { id: 33, name: "Юрий" },
    { id: 34, name: "Алёна" },
    { id: 35, name: "Виталий" },
    { id: 36, name: "Вероника" },
    { id: 37, name: "Артем" },
    { id: 38, name: "Зоя" },
    { id: 39, name: "Василий" },
    { id: 40, name: "Светлана" },
    { id: 41, name: "Олег" },
    { id: 42, name: "Кристина" },
    { id: 43, name: "Пётр" },
    { id: 44, name: "Анжела" },
    { id: 45, name: "Борис" },
    { id: 46, name: "Людмила" },
    { id: 47, name: "Егор" },
    { id: 48, name: "Ирина" },
    { id: 49, name: "Фёдор" },
    { id: 50, name: "Лариса" },
    { id: 51, name: "Эдуард" },
    { id: 52, name: "Тамара" },
    { id: 53, name: "Леонид" },
    { id: 54, name: "Валентина" },
    { id: 55, name: "Степан" },
    { id: 56, name: "Галина" },
    { id: 57, name: "Георгий" },
    { id: 58, name: "Нина" },
    { id: 59, name: "Вадим" },
    { id: 60, name: "Елена" },
    { id: 61, name: "Руслан" },
    { id: 62, name: "Эльвира" },
    { id: 63, name: "Альберт" },
    { id: 64, name: "Марина" },
    { id: 65, name: "Захар" },
    { id: 66, name: "Диана" },
    { id: 67, name: "Станислав" },
    { id: 68, name: "Жанна" },
    { id: 69, name: "Ярослав" },
    { id: 70, name: "Лидия" },
    { id: 71, name: "Адам" },
    { id: 72, name: "Вера" },
    { id: 73, name: "Виктор" },
    { id: 74, name: "Эмма" },
    { id: 75, name: "Геннадий" },
    { id: 76, name: "Оксана" },
    { id: 77, name: "Платон" },
    { id: 78, name: "Раиса" },
    { id: 79, name: "Альбина" },
    { id: 80, name: "Тимофей" },
    { id: 81, name: "Виолетта" },
    { id: 82, name: "Никита" },
    { id: 83, name: "Валерия" },
    { id: 84, name: "Лев" },
    { id: 85, name: "Римма" },
    { id: 86, name: "Роберт" },
    { id: 87, name: "Любовь" },
    { id: 88, name: "Вячеслав" },
    { id: 89, name: "Агата" },
    { id: 90, name: "Давид" },
    { id: 91, name: "Мирослава" },
    { id: 92, name: "Семён" },
    { id: 93, name: "Венера" },
    { id: 94, name: "Данил" },
    { id: 95, name: "Гузель" },
    { id: 96, name: "Илья" },
    { id: 97, name: "Рада" },
    { id: 98, name: "Тимур" },
    { id: 99, name: "Амелия" },
    { id: 100, name: "Владислав" },
  ],
};
